use_cuda : True
gpu_idx : 1
model:
  out_channels: 256
  activation: prelu
  hidden_channels: 256
  mode: 4
  num_layers: 2
  num_proj_hidden: 32
  tau: 0.4
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
optim:
  lr: 0.0001
  name : adam
  max_epoch : 50
  patience : 30
  weight_decay : 0.0005
dataset:
  name : WikiCS
  root : pyg_data
output:
  verbose : True
  save_dir : './saved_model'
  interval : 100
classifier:
  base_lr: 0.01
  name : adam
  max_epoch : 1500
  patience : 100
  run : 10
  weight_decay : 0.0