use_cuda : True
gpu_idx : 1
model:
  dropout: 0.5 
  n_layers: 2 
  in_channels: 1433
  hidden_channels: 512
  mode: 4
  num_layers: 2
  num_hidden: 512
  num_proj_hidden: 512
optim:
  lr: 0.0001
  lr2: 0.01
  tau: 0.5
  dfr1: 0.1
  dfr2: 0.1
  der1: 0.1
  der2: 0.1
  lv: 1
  cutway: 2
  cutrate: 1.0
  wd: 0
  wd2: 0.0004
  name : adam
  max_epoch : 50
  patience : 30
  weight_decay : 0.0005
dataset:
  name : WikiCS
  root : wikics
output:
  verbose : True
  save_dir : './saved_model'
  interval : 100
classifier:
  base_lr: 0.01
  name : adam
  max_epoch : 300
  patience : 1000
  run : 10
  weight_decay : 0.0