device: cuda:0
model:
  feat_drop: 0.1
  attn_drop: 0.3
  hidden_dim: 64
  sample_rate: [1, 18, 2]
  tau: 0.5  # hyperparameter. Refer to the original paper for definition
optim:
  lr: 0.001
  max_epoch : 500
  patience : 20
dataset:
  name : acm
  root : datasets
  target_type: 'movie'
  P: 3  # number of meta-paths
  nei_num: 3   # number of neighbors' types
classifier:   # evaluation
  base_lr: 0.01
  weight_decay: 0
  max_epoch: 100
  n_run: 50
