device: cuda:0
model:
  feat_drop: 0.4
  attn_drop: 0.35
  hidden_dim: 64
  sample_rate: [6]
  tau: 0.9  # hyperparameter. Refer to the original paper for definition
optim:
  lr: 0.0008
  max_epoch : 500
  patience : 30
dataset:
  name : acm
  root : datasets
  target_type: 'author'
  P: 3  # number of meta-paths
  nei_num: 1   # number of neighbors' types
classifier:   # evaluation
  base_lr: 0.01
  weight_decay: 0
  max_epoch: 100
  n_run: 50
