device: cuda:0
model:
  feat_drop: 0.5
  attn_drop: 0.5
  hidden_dim: 64
  sample_rate: [3, 8]
  tau: 0.5  # hyperparameter. Refer to the original paper for definition
optim:
  lr: 0.003
  max_epoch : 500
  patience : 40
dataset:
  name : acm
  root : datasets
  target_type: 'paper'
  P: 2  # number of meta-paths
  nei_num: 2   # number of neighbors' types
classifier:   # evaluation
  base_lr: 0.01
  weight_decay: 0
  max_epoch: 100
  n_run: 50
