use_cuda : True
gpu_idx : 3
model:
  dropout: 0.5 
  n_layers: 3
  in_channels: 745
  hidden_channels: 512
  alpha: 0.2
  t: 5
  batch_size: 8
  aug_type: 'ppr'
optim:
  base_lr: 0.0005
  name : adam
  max_epoch : 3000
  patience : 200
  weight_decay : 0.0005
  run: 1
classifier:
  base_lr: 0.001
  name : adam
  max_epoch : 30000
  patience : 500
  run : 10
  weight_decay : 0.0005
dataset:
  name : photo
  root : pyg_data
output:
  verbose : True
  save_dir : './saved_model'
  interval : 100
