use_cuda : True
gpu_idx : 0
model:
  dropout: 0.5 
  n_layers: 2 
  in_channels: 300
  hidden_channels: 256
  alpha: 0.2
  t: 5
  batch_size: 8
  aug_type: 'ppr'
optim:
  base_lr: 0.0001
  name : adam
  max_epoch : 3000
  patience : 200
  weight_decay : 0.0005
classifier:
  base_lr: 0.001
  name : adam
  max_epoch : 3000
  patience : 1000
  run : 10
  weight_decay : 0.0005
dataset:
  name : WikiCS
  root : wikics
output:
  verbose : True
  save_dir : './saved_model'
  interval : 100
  aaa:
    aaaa: 0
    bbbb: 0
