dataset: "photo"
root : 'pyg_data'
black_list: [4,5,6]
lr: 0.01
out_heads: 1
task_type: Node_Transductive
val_interval: 1
num_hidden_features: 8
to_undirected_at_neg: True
epochs: 1000
w_loss1: 100
w_loss2: 100
w_loss3: 1
margin1: 0.9
margin2: 0.9
dim: 128
cfg: [512, 128]
NewATop: 0
dropout: 0.1
NN: 1
num1: 200
wd: 0.0
weight_decay: 0.0001